DRM="*M"
DRM_RADEON = { value = " *M", comment = "For r300 or r600" }
DRM_AMDGPU = { value = " *M", comment = "For radeonsi" }
DRM_AMDGPU_SI="*"
DRM_AMDGPU_CIK="*"
DRM_AMD_DC="*"
DRM_NOUVEAU = { value = " *M", comment = "For nouveau" }
DRM_I915 = { value = " *M", comment = "For i915, crocus, or iris" }
DRM_VMWGFX = { value = " *M", comment = "For svga" }
DRM_VGEM = { value = " *M", comment = "For swrast" }
