# forced by !EXPERT
BLOCK = { value = '*', forced = true }
EFI='*'
PARTITION_ADVANCED='* '
EFI_PARTITION="*"
SYSFB_SIMPLEFB="*"
DRM="*"
DRM_FBDEV_EMULATION="*"
DRM_SIMPLEDRM="*"
FB="*"
# forced by VT && TTY, with !EXPERT VT and TTY are always set
FRAMEBUFFER_CONSOLE = { value = "*", forced = true }
VFAT_FS="*M"
EFIVAR_FS="*M"
# forced by both ACPI and PCI on a typical x86 desktop/server system
NLS = { value = "*", forced = "*" }
NLS_CODEPAGE_437="*M"
NLS_ISO8859_1="*M"
